### ISSUE TITLE
About classifier-free guidance (CFG) at inference.

### ISSUE THREAD

**Issue by eafn** [chenhaoxing/DiffUTE#11]
Could you please tell me if this work employs classifier-free guidance (CFG)? If so, what is the negative prompt, and what is the CFG scale value?

**Comment by eafn** [comment]
Do the other baseline methods employ classifier-free guidance (CFG)，such as SD, SD-FT?

**Comment by tydia** [comment]
This work does not use cfg. But you can implement it by treating embeddings of a glyph image with no text drawn as the null prompt. By training the model with certain probablity of just editing text given null prompt, you can implement and use classifier free guidance in inference.
