### ISSUE TITLE
关于vae训练的问题

### ISSUE THREAD

**Issue by jiang-111** [chenhaoxing/DiffUTE#12]
您好，我在渐进式训练vae的时候出现了一些问题，
S=64和S=128的阶段，将和训练集一样处理的图片经过vae encode再decode之后，图片上的文字可以辨认，
但是当S增加到256时，解码出来的图片上面文字非常不清晰，不能辨认，可是我的模型已经收敛了……
想知道vae训练的时候参数是怎么设置的呢？

**Comment by tydia** [comment]
https://openreview.net/forum?id=XKeSauhUdJ

作者在openreview审稿阶段上传的Supplementary Material提到了具体的训练细节，我照着里面提供的超参训vae没遇到什么问题。

hope it helps

**Comment by jiang-111** [comment]
> https://openreview.net/forum?id=XKeSauhUdJ
> 
> 作者在openreview审稿阶段上传的Supplementary Material提到了具体的训练细节，我照着里面提供的超参训vae没遇到什么问题。
> 
> hope it helps

谢谢！我来看看

**Comment by bjtuln** [comment]
请问finetune VAE不需要加上KL散度损失吗？

**Comment by chenhaoxing** [comment]
> 请问finetune VAE不需要加上KL散度损失吗？

可以加，应该能提升效果。我们当时做的还是比较糙。
