### ISSUE TITLE
Regarding package installation

### ISSUE THREAD

**Issue by jimmmarathon** [chenhaoxing/DiffUTE#13]
Thank you very much for your work. I have a question I would like to ask.
Regarding the following lines:
``
from pcache_fileio import fileio
``
``
from pcache_fileio.oss_conf import OssConfigFactory
``
``
from alps.pytorch.api.utils.web_access import 
``
What packages should I install to execute these three lines?

**Comment by chenhaoxing** [comment]
Hi, this is our internal data storage and reading method, you can not use these packages. Map the corresponding Dataloader.
