### ISSUE TITLE
About Input Data

### ISSUE THREAD

**Issue by baowuzhida** [chenhaoxing/DiffUTE#5]
In paper I seen that the embedding of the glyph image is the condition, and the the masked image latent vector 𝑥𝑚, mask 𝑚, and noisy image latent vector 𝑧𝑡 as the input.

I wounder how 𝑥𝑚, 𝑚, and 𝑧𝑡 be input? Is it just concat together? 

 Looking forward to your attention and response.

**Comment by chenhaoxing** [comment]
You can refer to the code implementation of inpainting in diffusers https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py.
